added logic.js file and random table filling
Ivan-Andr/psychological-test pull request #33
Opened 2023-02-19 12:28 UTC by Ivan-Andr

I added some chenges to random table filling, it works but positions of red and black numbers are same as in our first table.

2023-02-19 23:47 UTC, levnikan commented
I think the algorithm is correct, but initial way we set colors is wrong. The destribution of colors in not equal. Alternative solutions could be: 1) create an array of black objects [{index: 1, color:"black"},{index: 2, color:"black"}, ... {index: 25, color:"black"}], 2) 1) create an array of red objects [{index: 1, color:"red"}, {index: 2, color:"red"}, ... {index: 24, color:"red"}] 2) concatenate those two arrays into one 3) shuffle final array. And then we will simply check color value of each object upon iteration like tableArr[k].color === "red" ? cell.className = "table_cell_red" : cell.className = "table_cell_black"

2023-02-20 19:34 UTC, Ivan-Andr commented
I Added your version of array filling. But I can't get updated testNumber after form filling. I want to use it like starting value of red and black number arrays.

2023-02-21 23:06 UTC, levnikan requested changes

2023-02-21 23:06 UTC, levnikan commented on script.js
> +const tableArr2 = new Array(49);
why do you have same code here and below?

2023-02-21 23:06 UTC, levnikan commented on src/ui/table.js
> +function arrayFill(startElem) {
it's better to create 2 pure functions (one for table and one for red) and make them independent from the outer scope e.g. passing array as parameter and then return filled one.

2023-02-21 23:06 UTC, levnikan commented on src/ui/table.js
> +function arrayFill(startEl) {
I would call it `getBlackRedArray` and move into utils folder, same for shuffle, let's call it `getShuffledArray`. You can also add description to those functions if you wish https://stackoverflow.com/questions/73219300/how-can-i-add-a-description-to-a-function-in-javascript

2023-02-21 23:06 UTC, levnikan commented on src/ui/table.js
> +//////////////////var1/////////////
let's clean all the comments

2023-02-21 23:10 UTC, levnikan commented
> I Added your version of array filling. But I can't get updated testNumber after form filling. I want to use it like starting value of red and black number arrays. `// let startElem = userObject.tableNumber; // console.log(startElem, typeof startElem);`

you can try to add 2 more steps to the event listener https://github.com/Ivan-Andr/psychological-test/blob/issue%2311/src/ui/form.js#L51 1) delete the existing table and its children 2) generate it again and pass the number entered like table(numberOfTheTest)

2023-02-24 10:50 UTC, levnikan commented on src/ui/form.js
> +    table(shuffledArray(getBlackRedArr(Number(userObject.tableNumber))));
haha, that's a bit too much, better to write a couple of lines declaring new variables, but let's leave it for now

2023-02-24 10:51 UTC, levnikan approved these changes, later dismissed

2023-02-24 20:52 UTC, levnikan commented on src/ui/buttons.js
> +    if ((confirmWindow = window.confirm(`${message}`))) {
better would be to make it with the modal window, but let's proceed for now and create a tech debt ticket to improve it.

2023-02-24 20:52 UTC, levnikan approved these changes

2023-02-25 04:35 UTC, merged